#!/usr/bin/env bash
# Installs nginx server
apt-get update
apt-get install -y nginx

cat << EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    location / {
        try_files $uri $uri/ =404;
    }
}
EOF

echo "Hello World!" > /var/www/html/index.html

service nginx restart
